services:
  app:
    image: ghcr.io/lfpoulin/jpjr:latest
    container_name: jpjr_app
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: jpjr_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
