services:
  jpjr:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: 8ah/jpjr
    container_name: jpjr
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      jpjr_network:
        ipv4_address: 172.10.0.10

  ollama:
    image: ollama/ollama
    container_name: ollama
    runtime: nvidia
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      jpjr_network:
        ipv4_address: 172.10.0.20

  speaches:
    container_name: speaches
    image: ghcr.io/speaches-ai/speaches:latest-cuda-12.6.3
    build:
      args:
        BASE_IMAGE: nvidia/cuda:12.9.0-cudnn-runtime-ubuntu24.04
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - hf-hub-cache:/home/ubuntu/.cache/huggingface/hub
    environment:
      - enable_ui=false
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      jpjr_network:
        ipv4_address: 172.10.0.30

volumes:
  hf-hub-cache:
  ollama:

networks:
  jpjr_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24