services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: jpjr_app
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
    ports:
      - "443:443"
    restart: unless-stopped